# Generated by Django 4.1.7 on 2023-03-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_analysis_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='file',
        ),
    ]
