# Generated by Django 4.1.7 on 2023-03-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_remove_analysis_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='log_file',
            field=models.FileField(default='ex', upload_to=''),
            preserve_default=False,
        ),
    ]
