# Generated by Django 4.1.7 on 2023-03-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_alter_analysis_log_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='log_id',
            field=models.CharField(max_length=255),
        ),
    ]
