# Generated by Django 4.1.7 on 2023-03-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_alter_analysis_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='section',
            field=models.CharField(max_length=1, unique=True),
        ),
    ]
