# Generated by Django 4.1.7 on 2023-03-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_alter_analysis_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='section',
            field=models.CharField(max_length=1),
        ),
    ]
