# Generated by Django 4.1.7 on 2023-03-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_alter_analysis_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='description',
            field=models.TextField(),
        ),
    ]
