# Generated by Django 4.1.7 on 2023-03-26 00:11

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_alter_analysis_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='log_file',
            field=models.FileField(upload_to='', validators=[utils.validators.file_extension_validator]),
        ),
    ]
